# pull Cypress image
FROM cypress/included:latest

# create app directory
WORKDIR /usr/src/app

# bundle app source
COPY . .

# install node_modules
RUN npm run install-prod

# build client React JS
RUN CI=false npm run build-client

# run the app
CMD ["npm", "start"]
