const {
  countPG101A,
  countPG101C,
  countPG211A,
  countPG211C,
  countPG214,
  countPG206,
  countPG207,
  countPGPR201Baru,
  countPGS201,
  countPGS203,
  countPGPro01,
  countPGPro02,
  countPGPro01Combined,
  countGender,
  countMasa,
  countBp,
  countBPE,
  countKEPP,
  countTOD,
  countAdHocQuery,
} = require('./countHelperRegular');
const {
  countPPIM03,
  countPPIM04,
  countPPIM05,
  countBEGIN,
  countCPPC1,
  countCPPC2,
  countDEWASAMUDA,
  countOAP,
  countLiputanOA,
  countLiputanPenan,
  countKPBMPBHarian,
  countKPBMPBBulanan,
  countKOM,
  countPPR,
  countUTCRTC,
  countPPKPS,
  countPKAP2,
} = require('./countHelperKomuniti');

const reten_engine_version = '1.6.6';

module.exports = {
  // version
  reten_engine_version,
  // funcs
  countPG101A,
  countPG101C,
  countPG211A,
  countPG211C,
  countPG214,
  countPG206,
  countPG207,
  countPGPR201Baru,
  countPGS201,
  countPGS203,
  countPGPro01,
  countPGPro02,
  countPGPro01Combined,
  countGender,
  countMasa,
  countBp,
  countBPE,
  countKEPP,
  countTOD,
  countAdHocQuery,
  countPPIM03,
  countPPIM04,
  countPPIM05,
  countBEGIN,
  countCPPC1,
  countCPPC2,
  countDEWASAMUDA,
  countOAP,
  countLiputanOA,
  countLiputanPenan,
  countKOM,
  countKPBMPBHarian,
  countKPBMPBBulanan,
  countKOM,
  countPPR,
  countUTCRTC,
  countPPKPS,
  countPKAP2,
};
