const {
  countPG101A,
  countPG101C,
  countPG211A,
  countPG211C,
  countPG214,
  countPG206,
  countPG207,
  countPGPR201Baru,
  countPGS201,
  countPGS203,
  countPGPro01,
  countPGPro02,
  countPGPro01Combined,
  countGender,
  countMasa,
  countBp,
  countBPE,
  countKEPP,
  countTOD,
  countAdHocQuery,
} = require('../controllers/countHelper');
const {
  countPPIM03,
  countPPIM04,
  countBEGIN,
  countDEWASAMUDA,
  countOAP,
  countLiputanOAP,
  countKPBMPBHarian,
  countKPBMPBBulanan,
  countKOM,
} = require('../controllers/countHelperKomuniti');

module.exports = {
  countPG101A,
  countPG101C,
  countPG211A,
  countPG211C,
  countPG214,
  countPG206,
  countPG207,
  countPGPR201Baru,
  countPGS201,
  countPGS203,
  countPGPro01,
  countPGPro02,
  countPGPro01Combined,
  countGender,
  countMasa,
  countBp,
  countBPE,
  countKEPP,
  countTOD,
  countAdHocQuery,
  countPPIM03,
  countPPIM04,
  countBEGIN,
  countDEWASAMUDA,
  countOAP,
  countLiputanOAP,
  countKOM,
  countKPBMPBHarian,
  countKPBMPBBulanan,
  countKOM,
};
