// ini adalah senarai kod negeri dan daerah pentadbiran Gi-Ret

const emailGen = {
  Johor: {
    kodNegeri: '01',
    daerah: {
      'Batu Pahat': '01',
      'Johor Bahru': '02',
      Kluang: '03',
      'Kota Tinggi': '04',
      Kulai: '05',
      Mersing: '06',
      Muar: '07',
      Pontian: '08',
      Segamat: '09',
      Tangkak: '10',
    },
  },
  Kedah: {
    kodNegeri: '02',
    daerah: {
      Baling: '01',
      'Bandar Baharu': '02',
      'Kota Setar': '03',
      'Kuala Muda': '04',
      'Kubang Pasu': '05',
      Langkawi: '06',
      'Padang Terap': '07',
      Pendang: '08',
      Sik: '09',
      Yan: '10',
      Kulim: '11',
    },
  },
  Kelantan: {
    kodNegeri: '03',
    daerah: {
      Bachok: '01',
      'Gua Musang': '02',
      Jeli: '03',
      'Kota Bharu': '04',
      'Kuala Krai': '05',
      Machang: '06',
      'Pasir Mas': '07',
      'Pasir Putih': '08',
      'Tanah Merah': '09',
      Tumpat: '10',
    },
  },
  Melaka: {
    kodNegeri: '04',
    daerah: {
      'Alor Gajah': '01',
      Jasin: '02',
      'Melaka Tengah': '03',
    },
  },
  'Negeri Sembilan': {
    kodNegeri: '05',
    daerah: {
      Jelebu: '01',
      Jempol: '02',
      'Kuala Pilah': '03',
      'Port Dickson': '04',
      Rembau: '05',
      Seremban: '06',
      Tampin: '07',
    },
  },
  Pahang: {
    kodNegeri: '06',
    daerah: {
      Bentong: '01',
      Bera: '02',
      'Cameron Highland': '03',
      Jerantut: '04',
      'Kuala Lipis': '05',
      Kuantan: '06',
      Maran: '07',
      Pekan: '08',
      Raub: '09',
      Rompin: '10',
      Temerloh: '11',
    },
  },
  'Pulau Pinang': {
    kodNegeri: '07',
    daerah: {
      'Barat Daya': '01',
      'Seberang Perai Selatan': '02',
      'Seberang Perai Tengah': '03',
      'Seberang Perai Utara': '04',
      'Timur Laut': '05',
    },
  },
  Perak: {
    kodNegeri: '08',
    daerah: {
      'Batang Padang': '01',
      'Hilir Perak': '02',
      'Hulu Perak': '03',
      Kampar: '04',
      Kerian: '05',
      Kinta: '06',
      'Kuala Kangsar': '07',
      'Larut Matang': '08',
      Manjung: '09',
      Muallim: '10',
      'Perak Tengah': '11',
    },
  },
  Perlis: {
    kodNegeri: '09',
    daerah: {
      Arau: '01',
      Kangar: '02',
    },
  },
  Selangor: {
    kodNegeri: '10',
    daerah: {
      Gombak: '01',
      'Hulu Langat': '02',
      'Hulu Selangor': '03',
      Klang: '04',
      'Kuala Langat': '05',
      'Kuala Selangor': '06',
      Petaling: '07',
      'Sabak Bernam': '08',
      Sepang: '09',
    },
  },
  Terengganu: {
    kodNegeri: '11',
    daerah: {
      Besut: '01',
      Dungun: '02',
      'Hulu Terengganu': '03',
      Kemaman: '04',
      'Kuala Nerus': '05',
      'Kuala Terengganu': '06',
      Marang: '07',
      Setiu: '08',
    },
  },
  Sabah: {
    kodNegeri: '12',
    daerah: {
      Beaufort: '01',
      Beluran: '02',
      Keningau: '03',
      Kinabatangan: '04',
      'Kota Belud': '05',
      'Kota Kinabalu': '06',
      'Kota Marudu': '07',
      'Kuala Penyu': '08',
      Kudat: '09',
      Kunak: '10',
      'Lahad Datu': '11',
      Nabawan: '12',
      Papar: '13',
      Penampang: '14',
      Pitas: '15',
      Putatan: '16',
      Ranau: '17',
      Sandakan: '18',
      Semporna: '19',
      Sipitang: '20',
      Tambunan: '21',
      Tawau: '22',
      Telupid: '23',
      Tenom: '24',
      Tongod: '25',
      Tuaran: '26',
    },
  },
  Sarawak: {
    kodNegeri: '13',
    daerah: {
      Betong: '01',
      Bintulu: '02',
      Kapit: '03',
      Kuching: '04',
      Limbang: '05',
      Miri: '06',
      Mukah: '07',
      Samarahan: '08',
      Sarikei: '09',
      Sibu: '10',
      'Sri Aman': '11',
    },
  },
  'WP Kuala Lumpur': {
    kodNegeri: '14',
    daerah: {
      'Zon Cheras': '01',
      'Zon Kepong': '02',
      'Zon Lembah Pantai': '03',
      'Zon Titiwangsa': '04',
    },
  },
  'WP Labuan': {
    kodNegeri: '15',
    daerah: {
      'WP Labuan': '01',
    },
  },
  'WP Putrajaya': {
    kodNegeri: '16',
    daerah: {
      'WP Putrajaya': '01',
    },
  },
};

module.exports = emailGen;
