const emailGen = {
  johor: {
    kodNegeri: '01',
    daerah: {
      'batu pahat': '01',
      'johor bahru': '02',
      kluang: '03',
      'kota tinggi': '04',
      kulai: '05',
      mersing: '06',
      muar: '07',
      pontian: '08',
      segamat: '09',
    },
  },
  kedah: {
    kodNegeri: '02',
    daerah: {
      baling: '01',
      'bandar baharu': '02',
      'kota setar': '03',
      'kuala muda': '04',
      'kubang pasu': '05',
      langkawi: '06',
      'padang terap': '07',
      pendang: '08',
      sik: '09',
      yan: '10',
    },
  },
  kelantan: {
    kodNegeri: '03',
    daerah: {
      bachok: '01',
      'gua musang': '02',
      jeli: '03',
      'kota bharu': '04',
      'kuala krai': '05',
      machang: '06',
      'pasir mas': '07',
      'pasir putih': '08',
      'tanah merah': '09',
      tumpat: '10',
    },
  },
  melaka: {
    kodNegeri: '04',
    daerah: {
      'alor gajah': '01',
      jasin: '02',
      'melaka tengah': '03',
    },
  },
  negeriSembilan: {
    kodNegeri: '05',
    daerah: {
      jelebu: '01',
      jempol: '02',
      'kuala pilah': '03',
      'port dickson': '04',
      rembau: '05',
      seremban: '06',
      tampin: '07',
    },
  },
  pahang: {
    kodNegeri: '06',
    daerah: {
      bentong: '01',
      bera: '02',
      'cameron highlands': '03',
      jerantut: '04',
      'kuala lipis': '05',
      kuantan: '06',
      maran: '07',
      pekan: '08',
      raub: '09',
      rompin: '10',
      temerloh: '11',
    },
  },
  pulauPinang: {
    kodNegeri: '07',
    daerah: {
      'barat daya': '01',
      'seberang prai selatan': '02',
      'seberang prai timur': '03',
      'seberang prai utara': '04',
      'timur laut': '05',
    },
  },
  perak: {
    kodNegeri: '08',
    daerah: {
      'batang padang': '01',
      'hilir perak': '02',
      kampar: '03',
      kerian: '04',
      kinta: '05',
      'kuala kangsar': '06',
      'larut matang selama': '07',
      manjung: '08',
      muallim: '09',
      'perak tengah': '10',
    },
  },
  perlis: {
    kodNegeri: '09',
    daerah: {
      arau: '01',
      kangar: '02',
    },
  },
  selangor: {
    kodNegeri: '10',
    daerah: {
      gombak: '01',
      'hulu langat': '02',
      'hulu selangor': '03',
      klang: '04',
      'kuala langat': '05',
      'kuala selangor': '06',
      petaling: '07',
      'sabak bernam': '08',
      sepang: '09',
    },
  },
  terengganu: {
    kodNegeri: '11',
    daerah: {
      besut: '01',
      dungun: '02',
      'hulu terengganu': '03',
      kemaman: '04',
      'kuala nerus': '05',
      'kuala terengganu': '06',
      marang: '07',
      setiu: '08',
    },
  },
  sabah: {
    kodNegeri: '12',
    daerah: {
      beaufort: '01',
      beluran: '02',
      keningau: '03',
      kinabatangan: '04',
      'kota belud': '05',
      'kota kinabalu': '06',
      'kota marudu': '07',
      'kuala penyu': '08',
      kudat: '09',
      kunak: '10',
      'lahad datu': '11',
      nabawan: '12',
      papar: '13',
      penampang: '14',
      pitas: '15',
      putatan: '16',
      ranau: '17',
      sandakan: '18',
      semporna: '19',
      sipitang: '20',
      tambunan: '21',
      tawau: '22',
      telupid: '23',
      tenom: '24',
      tongod: '25',
      tuaran: '26',
    },
  },
  sarawak: {
    kodNegeri: '13',
    daerah: {
      betong: '01',
      bintulu: '02',
      kapit: '03',
      kuching: '04',
      limbang: '05',
      miri: '06',
      mukah: '07',
      samarahan: '08',
      sarikei: '09',
      sibu: '10',
      'sri aman': '11',
    },
  },
  kualaLumpur: {
    kodNegeri: '14',
    daerah: {
      'zon cheras': '01',
      'zon kepong': '02',
      'zon lembah pantai': '03',
      'zon titiwangsa': '04',
    },
  },
  labuan: {
    kodNegeri: '15',
    daerah: {
      labuan: '01',
    },
  },
  putrajaya: {
    kodNegeri: '16',
    daerah: {
      'zon putrajaya': '01',
    },
  },
};

module.exports = emailGen;
