name: Automerge
on:
  workflow_dispatch:
    inputs:
      pull-request:
        description: Trigger Automerge
        required: false

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.15.5'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
