name: Sync unstable-nightly into other branch
on:
  push:
    branches:
      - unstable-nightly

jobs:
  sync-branch-nocturnalmc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'nocturnalmc'
          LABELS: '["automerge"]'
  sync-branch-c4lyp5o:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'c4lyp5o'
          LABELS: '["automerge"]'
  sync-branch-Dvachini:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'Dvachini'
          LABELS: '["automerge"]'
  sync-branch-t4qi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 't4qi'
          LABELS: '["automerge"]'
  # sync-branch-hadigit01:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - name: Opening pull request
  #       id: pull
  #       uses: nocturnalmc/sync-branches@v1.5.0
  #       with:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #         FROM_BRANCH: 'unstable-nightly'
  #         TO_BRANCH: 'hadigit01'
  #         LABELS: '["automerge"]'
  # sync-branch-Xarrenleong:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - name: Opening pull request
  #       id: pull
  #       uses: nocturnalmc/sync-branches@v1.5.0
  #       with:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #         FROM_BRANCH: 'unstable-nightly'
  #         TO_BRANCH: 'Xarrenleong'
  #         LABELS: '["automerge"]'
