name: Sync unstable-nightly into other branch
on:
  push:
    branches:
      - unstable-nightly

jobs:
  sync-branch-admin-id-sekolah:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'nocturnalmc'
          LABELS: '["automerge"]'
  sync-branch-admin-overhaul:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'c4lyp5o'
          LABELS: '["automerge"]'
  sync-branch-erkm-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'Dvachini'
          LABELS: '["automerge"]'
  sync-branch-generate-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'hadigit01'
          LABELS: '["automerge"]'
  sync-branch-landing-selection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'Xarrenleong'
          LABELS: '["automerge"]'
