name: Sync unstable-nightly into other branch
on:
  push:
    branches:
      - unstable-nightly

jobs:
  sync-branch-admin-id-sekolah:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'admin-id-sekolah'
          LABELS: '["automerge"]'
  sync-branch-admin-overhaul:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'admin-overhaul'
          LABELS: '["automerge"]'
  sync-branch-erkm-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'erkm-integration'
          LABELS: '["automerge"]'
  sync-branch-generate-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'generate-debug'
          LABELS: '["automerge"]'
  sync-branch-landing-selection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'landing-selection'
          LABELS: '["automerge"]'
  sync-branch-overhaul-sekolah:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'overhaul-sekolah'
          LABELS: '["automerge"]'
  sync-branch-responsive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'responsive'
          LABELS: '["automerge"]'
  sync-branch-status-harian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'status-harian'
          LABELS: '["automerge"]'
  sync-branch-umum-kaunter-overhaul:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: nocturnalmc/sync-branches@v1.5.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'unstable-nightly'
          TO_BRANCH: 'umum-kaunter-overhaul'
          LABELS: '["automerge"]'
